<h1 style="display: flex; align-items: center; justify-content: center;">
  <img src="../../pictures/garch.png" width="100" style="margin-right: 10px;"/>
  🧹 Xử lý dữ liệu (Garch Preprocessing)
</h1>

### Import thư viện 📦

In [142]:

# Import các thư viện cần thiết
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
import warnings
warnings.filterwarnings("ignore")

### Định nghĩa hàm sử dụng ⚙️

In [143]:

# Load dữ liệu đã xử lý từ bước preprocessing
df = pd.read_csv(r"C:\học Python\Data Science and Atifficial Interligent\Các project data science và AI\Data Analsys\Phân tích dữ liệu và xây dựng hybrid model trong việc dự đoán volatility của Bitcoin tại thi trường crypto toàn cầu\data\Bitcoin_time_series_processed.csv")
df.drop(columns='Unnamed: 0',inplace=True)
df

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
0,2018-02-01 00:00:00,10285.10,10335.00,10215.07,10263.18,594.441290,276.384030,0.414383,-157.324165,-60.240144,11710.140938,11732.920935,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.561406
1,2018-02-01 01:00:00,10263.18,10328.98,10216.00,10247.49,591.515725,275.414274,0.414405,-157.144845,-61.057994,11703.588708,11726.744507,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.557828
2,2018-02-01 02:00:00,10249.43,10317.73,10176.89,10199.61,479.412562,274.615613,0.414454,-156.598525,-62.014479,11696.921833,11720.394675,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.556120
3,2018-02-01 03:00:00,10199.61,10250.79,9959.04,10069.80,739.435309,274.717301,0.414138,-155.131977,-63.408817,11689.046417,11713.531496,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534316
4,2018-02-01 04:00:00,10069.77,10256.00,10000.01,10245.79,649.939854,274.606160,0.413726,-158.422871,-64.105200,11681.703208,11707.428621,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70822,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.159140,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922
70823,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.929610,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833
70824,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.248790,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838
70825,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.875480,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167
70826,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.647290,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911

In [144]:
df.head()

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
0,2018-02-01 00:00:00,10285.10,10335.00,10215.07,10263.18,594.441290,276.384030,0.414383,-157.324165,-60.240144,11710.140938,11732.920935,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.561406
1,2018-02-01 01:00:00,10263.18,10328.98,10216.00,10247.49,591.515725,275.414274,0.414405,-157.144845,-61.057994,11703.588708,11726.744507,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.557828
2,2018-02-01 02:00:00,10249.43,10317.73,10176.89,10199.61,479.412562,274.615613,0.414454,-156.598525,-62.014479,11696.921833,11720.394675,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.556120
3,2018-02-01 03:00:00,10199.61,10250.79,9959.04,10069.80,739.435309,274.717301,0.414138,-155.131977,-63.408817,11689.046417,11713.531496,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534316
4,2018-02-01 04:00:00,10069.77,10256.00,10000.01,10245.79,649.939854,274.606160,0.413726,-158.422871,-64.105200,11681.703208,11707.428621,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534426

In [145]:
df.tail()

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual
70822,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.15914,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922
70823,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.92961,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833
70824,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.24879,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838
70825,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.87548,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167
70826,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.64729,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70827 entries, 0 to 70826
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             70827 non-null  object
 1   open                  70827 non-null  float64
 2   high                  70827 non-null  float64
 3   low                   70827 non-null  float64
 4   close                 70827 non-null  float64
 5   volume                70827 non-null  float64
 6   ATR                   70827 non-null  float64
 7   BB_width_norm         70827 non-null  float64
 8   RSI                   70827 non-null  float64
 9   MACD_Hist             70827 non-null  float64
 10  MA20                  70827 non-null  float64
 11  EMA20                 70827 non-null  float64
 12  Date                  70827 non-null  object
 13  CFGI                  70827 non-null  float64
 14  BTC Dominance         70827 non-null  float64
 15  Total CMC             70827 non-null  float64
 16  USDTD                 70827 non-null  float64
 17  Bitcoin CMC           70827 non-null  float64
 18  volatility_14_annual  70827 non-null  float64
dtypes: float64(17), object(2)
memory usage: 10.3+ MB

In [147]:

# tính log_return dựa trên giá, bởi vì model garch chỉ học với dữ liệu đầu vào là log_return
df['log_return'] = np.log(df['close'] / df['close'].shift(1))
df = df.dropna()
df

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual,log_return
1,2018-02-01 01:00:00,10263.18,10328.98,10216.00,10247.49,591.515725,275.414274,0.414405,-157.144845,-61.057994,11703.588708,11726.744507,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.557828,-0.001530
2,2018-02-01 02:00:00,10249.43,10317.73,10176.89,10199.61,479.412562,274.615613,0.414454,-156.598525,-62.014479,11696.921833,11720.394675,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.556120,-0.004683
3,2018-02-01 03:00:00,10199.61,10250.79,9959.04,10069.80,739.435309,274.717301,0.414138,-155.131977,-63.408817,11689.046417,11713.531496,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534316,-0.012809
4,2018-02-01 04:00:00,10069.77,10256.00,10000.01,10245.79,649.939854,274.606160,0.413726,-158.422871,-64.105200,11681.703208,11707.428621,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534426,0.017326
5,2018-02-01 05:00:00,10245.00,10275.47,10193.45,10238.00,387.674066,273.463215,0.413547,-158.332202,-64.794388,11674.803208,11701.318730,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534336,-0.000761
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70822,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.159140,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922,0.003251
70823,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.929610,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833,0.001375
70824,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.248790,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838,0.000377
70825,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.875480,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167,-0.003725
70826,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.647290,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911,-0.001078

In [148]:

# scaler dữ liệu
df['log_return'] = df['log_return'] * 100
df

,timestamp,open,high,low,close,volume,ATR,BB_width_norm,RSI,MACD_Hist,MA20,EMA20,Date,CFGI,BTC Dominance,Total CMC,USDTD,Bitcoin CMC,volatility_14_annual,log_return
1,2018-02-01 01:00:00,10263.18,10328.98,10216.00,10247.49,591.515725,275.414274,0.414405,-157.144845,-61.057994,11703.588708,11726.744507,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.557828,-0.152994
2,2018-02-01 02:00:00,10249.43,10317.73,10176.89,10199.61,479.412562,274.615613,0.414454,-156.598525,-62.014479,11696.921833,11720.394675,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.556120,-0.468331
3,2018-02-01 03:00:00,10199.61,10250.79,9959.04,10069.80,739.435309,274.717301,0.414138,-155.131977,-63.408817,11689.046417,11713.531496,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534316,-1.280864
4,2018-02-01 04:00:00,10069.77,10256.00,10000.01,10245.79,649.939854,274.606160,0.413726,-158.422871,-64.105200,11681.703208,11707.428621,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534426,1.732604
5,2018-02-01 05:00:00,10245.00,10275.47,10193.45,10238.00,387.674066,273.463215,0.413547,-158.332202,-64.794388,11674.803208,11701.318730,2018-02-01,30.0,38.130953,3.972854e+11,0.541264,1.514887e+11,1.534336,-0.076060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70822,2026-03-10 23:00:00,69721.58,69981.80,69698.46,69948.63,1165.159140,630.619773,0.125565,22715.462812,798.079696,67678.468042,68793.166000,2026-03-10,13.0,59.352780,2.357494e+12,7.801736,1.399238e+12,0.613922,0.325123
70823,2026-03-11 00:00:00,69948.64,70173.25,69759.63,70044.87,728.929610,629.331941,0.125669,15875.054066,799.139303,67685.964667,68798.370590,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.613833,0.137492
70824,2026-03-11 01:00:00,70044.87,70144.00,69880.00,70071.26,947.248790,627.163799,0.125801,14663.557223,800.221240,67692.641000,68803.663270,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.599838,0.037669
70825,2026-03-11 02:00:00,70071.26,70119.59,69614.00,69810.72,1612.875480,626.442292,0.125898,61217.518220,800.267129,67698.840000,68807.850616,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.600167,-0.372514
70826,2026-03-11 03:00:00,69810.73,69887.11,69669.88,69735.51,217.647290,624.013733,0.125992,757700.798537,799.979867,67704.578750,68811.707827,2026-03-11,15.0,59.333411,2.350619e+12,7.823834,1.394702e+12,0.598911,-0.107792

In [149]:

# Kiểm định stationary
result = adfuller(df['log_return'])
print("ADF Statistic:", result[0])
print("p-value:", result[1])

ADF Statistic: -37.12783294533974
p-value: 0.0

In [150]:

# lấy ra những cột cần thiết để training model
bitcoin_garch_dataset = pd.DataFrame()
bitcoin_garch_dataset['timestamp'] = df['timestamp']
bitcoin_garch_dataset['volatility_14_annual'] = df['volatility_14_annual']
bitcoin_garch_dataset['log_return'] = df['log_return']
bitcoin_garch_dataset

                 timestamp  volatility_14_annual  log_return
1      2018-02-01 01:00:00              1.557828   -0.152994
2      2018-02-01 02:00:00              1.556120   -0.468331
3      2018-02-01 03:00:00              1.534316   -1.280864
4      2018-02-01 04:00:00              1.534426    1.732604
5      2018-02-01 05:00:00              1.534336   -0.076060
...                    ...                   ...         ...
70822  2026-03-10 23:00:00              0.613922    0.325123
70823  2026-03-11 00:00:00              0.613833    0.137492
70824  2026-03-11 01:00:00              0.599838    0.037669
70825  2026-03-11 02:00:00              0.600167   -0.372514
70826  2026-03-11 03:00:00              0.598911   -0.107792

[70826 rows x 3 columns]

In [ ]:

# Xuất dữ liệu sang file .csv
bitcoin_garch_dataset.to_csv("bitcoin_garch_dataset.csv")